- name: ping playbook
  host: web
  tasks: list of servers
  - name: ping the server
    ansible.builtin.ping:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
    ansible.builtin.service:
      name: nginx
      state: started



