- name: variables from file
  hosts: localhost
  vars_files:
    - variables.yaml
  tasks:
  - name: playing with variables from file
    debug:
     msg: "I am learning {{Course}}, Tained by {{Trainer}}, with a duration of {{Time}}"