- name: play with variables using prompt
  hosts: localhost
  vars_prompt:
    - name: username
      prompt: what is your username?
      private: False

    - name: password
      prompt: Please enter your password here
      private: True

  tasks:
   - name: variables using prompt
     ansible.builtin.debug:
      msg: "logged in as {{username}}, with passwd as {{password}}"
