- name: playing with variables from command args
  hosts: localhost
  # vars_files:
  #  - variables.yaml
  vars_prompt:
    - name: PERSON
      prompt: please enter your name
      private: false
    
    - name: WISHES
      prompt: please enter WISHES
      private: true
     
  vars:
    PERSON: "Gopifromplay"
    WISHES: "Morningfromplay"

  tasks:
  - name: variables from args

    # vars:
    #  PERSON: "Gopi from task"
    #  WISHES: "Morning from task"
     
    ansible.builtin.debug:
     msg: "Hi {{PERSON}}, Good {{WISHES}}" 

  # Preferences
     # CMD
     # task
     # file