# playing with data types
- name: diff data types
  hosts: localhost
  vars: #key valuse pair
    NAME: gopi
    skills: #list types
    - Devops
    - shell
    - linux
    - ansible
    - docker
    Experience: #map tyoe
      Devops: 3 
      AWS: 3 
      GCP: 2
    Trainer: true #boolean

  tasks:
  - name: key value
    ansible.builtin.debug:
     msg: "name: {{NAME}}"

  - name: print lists
    ansible.builtin.debug:
     msg: " list: {{skills}}"

  - name: print maps
    ansible.builtin.debug:
     msg: "experience: {{Experience}}}"

  - name: print boolean
    ansible.builtin.debug:
     msg: "is he tainer: {{Trainer}}"

