- name: playbooks to work with conditions
  hosts: localhost
  tasks: 
  - name: check roboshop user exists or not
    ansible.builtin.command: id roboshop
    register: user
    ignore_errors: true

  - name: printing the variable
    ansible.builtin.debug:
     msg: "user is {{user}}"