- name: playbooks to work with conditions
  hosts: localhost
  tasks: 
  - name: check roboshop user exists or not
    ansible.builtin.command: id roboshop
    register: user
    ignore_errors: true

  - name: printing the variable
    ansible.builtin.debug:
     msg: "User is {{user}}"

  - name: printing exit status or return code
    ansible.builtin.debug:
     msg: "stats is {{user.rc}}"

# while: user.rc != 0