- name: loops
  hosts: localhost
  tasks:
  # - name: print persons
  #   ansible.builtin.debug:
  #    msg: "Hello user {{item}}"
  #   loop:
  #     - gopi
  #     - raju
  #     - ramu
  #     - shannu
   - name: packages installation
     ansible.builtin.package:
        name: "{{item}}"
        state: present
     loop:
       - git
       - mysql
       - postfix
  


  